default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: craftlink_development

test:
  <<: *default
  database: craftlink_test

production:
  <<: *default
  database: craftlink_production
  username: craftlink
  password: <%= ENV["CRAFTLINK_DATABASE_PASSWORD"] %>
